services:
  - type: web
    name: devvoid-backend
    env: node
    buildCommand: |
      npm install && 
      npm install --save-dev @types/node @types/express @types/jest @types/cors @types/mongoose @types/bcryptjs @types/jsonwebtoken @types/winston @types/dotenv @types/express-validator && 
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /api/health
    autoDeploy: true 